/** Auto-generated by scripts/sync-local-images.mjs — do not edit manually */

export const VILLA_ASHOKA_GALLERY = [
  "/images/villas/ashoka/01-first.webp",
  "/images/villas/ashoka/02-img-7840.webp",
  "/images/villas/ashoka/03-img-7842.webp",
  "/images/villas/ashoka/04-img-7848.webp",
  "/images/villas/ashoka/05-img-7851.webp",
  "/images/villas/ashoka/06-img-7854.webp",
  "/images/villas/ashoka/07-img-7855.webp",
  "/images/villas/ashoka/08-img-7856.webp",
  "/images/villas/ashoka/09-img-7857.webp",
  "/images/villas/ashoka/10-img-7858.webp",
  "/images/villas/ashoka/11-img-7859.webp",
  "/images/villas/ashoka/12-img-7860.webp",
  "/images/villas/ashoka/13-img-7863.webp",
  "/images/villas/ashoka/14-img-7868.webp",
  "/images/villas/ashoka/15-last.webp",
] as const;

export const VILLA_BOUGAINVILLE_GALLERY = [
  "/images/villas/bougainville/01-first.webp",
  "/images/villas/bougainville/02-img-7807.webp",
  "/images/villas/bougainville/03-img-7810.webp",
  "/images/villas/bougainville/04-img-7814.webp",
  "/images/villas/bougainville/05-img-7815.webp",
  "/images/villas/bougainville/06-img-7816.webp",
  "/images/villas/bougainville/07-img-7817.webp",
  "/images/villas/bougainville/08-img-7818.webp",
  "/images/villas/bougainville/09-img-7822.webp",
  "/images/villas/bougainville/10-img-7825.webp",
  "/images/villas/bougainville/11-img-7827.webp",
  "/images/villas/bougainville/12-img-7829.webp",
  "/images/villas/bougainville/13-img-7830.webp",
  "/images/villas/bougainville/14-img-7831.webp",
  "/images/villas/bougainville/15-img-7834.webp",
  "/images/villas/bougainville/16-last.webp",
] as const;

export const VILLA_KAYU_GALLERY = [
  "/images/villas/kayu/01-1.webp",
  "/images/villas/kayu/02-2.webp",
  "/images/villas/kayu/03-3.webp",
  "/images/villas/kayu/04-4.webp",
  "/images/villas/kayu/05-5.webp",
  "/images/villas/kayu/06-6.webp",
  "/images/villas/kayu/07-7.webp",
  "/images/villas/kayu/08-8.webp",
  "/images/villas/kayu/09-9.webp",
  "/images/villas/kayu/10-10.webp",
  "/images/villas/kayu/11-14.webp",
  "/images/villas/kayu/12-16.webp",
  "/images/villas/kayu/13-17.webp",
] as const;

export const VILLA_KRISNA_GALLERY = [
  "/images/villas/krisna/01-first.webp",
  "/images/villas/krisna/02-img-7910.webp",
  "/images/villas/krisna/03-img-7916.webp",
  "/images/villas/krisna/04-img-7920.webp",
  "/images/villas/krisna/05-img-7921.webp",
  "/images/villas/krisna/06-img-7923.webp",
  "/images/villas/krisna/07-img-7924.webp",
  "/images/villas/krisna/08-img-7929.webp",
  "/images/villas/krisna/09-last.webp",
] as const;

export const VILLA_LILI_GALLERY = [
  "/images/villas/lili/01-msg5073668127-110709.webp",
  "/images/villas/lili/02-msg5073668127-110710.webp",
  "/images/villas/lili/03-msg5073668127-110717.webp",
  "/images/villas/lili/04-msg5073668127-110718.webp",
  "/images/villas/lili/05-msg5073668127-110719.webp",
  "/images/villas/lili/06-msg5073668127-110720.webp",
  "/images/villas/lili/07-msg5073668127-110721.webp",
  "/images/villas/lili/08-msg5073668127-110722.webp",
  "/images/villas/lili/09-msg5073668127-110734.webp",
  "/images/villas/lili/10-msg5073668127-110735.webp",
  "/images/villas/lili/11-msg5073668127-110736.webp",
] as const;

export const VILLA_LOTUS_GALLERY = [
  "/images/villas/lotus/01-first.webp",
  "/images/villas/lotus/02-img-7963.webp",
  "/images/villas/lotus/03-img-7966.webp",
  "/images/villas/lotus/04-img-7967.webp",
  "/images/villas/lotus/05-img-7969.webp",
  "/images/villas/lotus/06-img-7970.webp",
  "/images/villas/lotus/07-img-7971.webp",
  "/images/villas/lotus/08-img-7972.webp",
  "/images/villas/lotus/09-img-7973.webp",
  "/images/villas/lotus/10-img-7976.webp",
  "/images/villas/lotus/11-img-7977.webp",
  "/images/villas/lotus/12-img-7978.webp",
  "/images/villas/lotus/13-img-7979.webp",
  "/images/villas/lotus/14-img-7982.webp",
  "/images/villas/lotus/15-img-7983.webp",
  "/images/villas/lotus/16-last.webp",
] as const;

export const VILLA_MONSTERA_GALLERY = [
  "/images/villas/monstera/01-first.webp",
  "/images/villas/monstera/02-img-7936.webp",
  "/images/villas/monstera/03-img-7938.webp",
  "/images/villas/monstera/04-img-7941.webp",
  "/images/villas/monstera/05-img-7944.webp",
  "/images/villas/monstera/06-img-7946.webp",
  "/images/villas/monstera/07-img-7950.webp",
  "/images/villas/monstera/08-img-7951.webp",
  "/images/villas/monstera/09-img-7952.webp",
  "/images/villas/monstera/10-img-7953.webp",
  "/images/villas/monstera/11-img-7955.webp",
  "/images/villas/monstera/12-img-7956.webp",
  "/images/villas/monstera/13-last.webp",
] as const;

export const VILLA_TUNJUNG_GALLERY = [
  "/images/villas/tunjung/01-first.webp",
  "/images/villas/tunjung/02-img-7878.webp",
  "/images/villas/tunjung/03-img-7879.webp",
  "/images/villas/tunjung/04-img-7884.webp",
  "/images/villas/tunjung/05-img-7888.webp",
  "/images/villas/tunjung/06-img-7890.webp",
  "/images/villas/tunjung/07-img-7894.webp",
  "/images/villas/tunjung/08-img-7895.webp",
  "/images/villas/tunjung/09-img-7899.webp",
  "/images/villas/tunjung/10-img-7902.webp",
  "/images/villas/tunjung/11-img-7904.webp",
  "/images/villas/tunjung/12-last.webp",
] as const;

