/** Auto-generated by scripts/sync-local-images.mjs — do not edit manually */

export const VILLA_ASHOKA_GALLERY = [
  "/images/villas/ashoka/01-first.jpg",
  "/images/villas/ashoka/02-img-7840.jpg",
  "/images/villas/ashoka/03-img-7842.jpg",
  "/images/villas/ashoka/04-img-7848.jpg",
  "/images/villas/ashoka/05-img-7851.jpg",
  "/images/villas/ashoka/06-img-7854.jpg",
  "/images/villas/ashoka/07-img-7855.jpg",
  "/images/villas/ashoka/08-img-7856.jpg",
  "/images/villas/ashoka/09-img-7857.jpg",
  "/images/villas/ashoka/10-img-7858.jpg",
  "/images/villas/ashoka/11-img-7859.jpg",
  "/images/villas/ashoka/12-img-7860.jpg",
  "/images/villas/ashoka/13-img-7863.jpg",
  "/images/villas/ashoka/14-img-7868.jpg",
  "/images/villas/ashoka/15-last.jpg",
] as const;

export const VILLA_BOUGAINVILLE_GALLERY = [
  "/images/villas/bougainville/01-first.jpg",
  "/images/villas/bougainville/02-img-7807.jpg",
  "/images/villas/bougainville/03-img-7810.jpg",
  "/images/villas/bougainville/04-img-7814.jpg",
  "/images/villas/bougainville/05-img-7815.jpg",
  "/images/villas/bougainville/06-img-7816.jpg",
  "/images/villas/bougainville/07-img-7817.jpg",
  "/images/villas/bougainville/08-img-7818.jpg",
  "/images/villas/bougainville/09-img-7822.jpg",
  "/images/villas/bougainville/10-img-7825.jpg",
  "/images/villas/bougainville/11-img-7827.jpg",
  "/images/villas/bougainville/12-img-7829.jpg",
  "/images/villas/bougainville/13-img-7830.jpg",
  "/images/villas/bougainville/14-img-7831.jpg",
  "/images/villas/bougainville/15-img-7834.jpg",
  "/images/villas/bougainville/16-last.jpg",
] as const;

export const VILLA_KAYU_GALLERY = [
  "/images/villas/kayu/01-1.jpg",
  "/images/villas/kayu/02-2.jpg",
  "/images/villas/kayu/03-3.jpg",
  "/images/villas/kayu/04-4.jpg",
  "/images/villas/kayu/05-5.jpg",
  "/images/villas/kayu/06-6.jpg",
  "/images/villas/kayu/07-7.jpg",
  "/images/villas/kayu/08-8.jpg",
  "/images/villas/kayu/09-9.jpg",
  "/images/villas/kayu/10-10.jpg",
  "/images/villas/kayu/11-14.jpg",
  "/images/villas/kayu/12-16.jpg",
  "/images/villas/kayu/13-17.jpg",
] as const;

export const VILLA_KRISNA_GALLERY = [
  "/images/villas/krisna/01-first.jpg",
  "/images/villas/krisna/02-img-7910.jpg",
  "/images/villas/krisna/03-img-7916.jpg",
  "/images/villas/krisna/04-img-7920.jpg",
  "/images/villas/krisna/05-img-7921.jpg",
  "/images/villas/krisna/06-img-7923.jpg",
  "/images/villas/krisna/07-img-7924.jpg",
  "/images/villas/krisna/08-img-7929.jpg",
  "/images/villas/krisna/09-last.jpg",
] as const;

export const VILLA_LILI_GALLERY = [
  "/images/villas/lili/01-msg5073668127-110709.jpg",
  "/images/villas/lili/02-msg5073668127-110710.jpg",
  "/images/villas/lili/03-msg5073668127-110717.jpg",
  "/images/villas/lili/04-msg5073668127-110718.jpg",
  "/images/villas/lili/05-msg5073668127-110719.jpg",
  "/images/villas/lili/06-msg5073668127-110720.jpg",
  "/images/villas/lili/07-msg5073668127-110721.jpg",
  "/images/villas/lili/08-msg5073668127-110722.jpg",
  "/images/villas/lili/09-msg5073668127-110734.jpg",
  "/images/villas/lili/10-msg5073668127-110735.jpg",
  "/images/villas/lili/11-msg5073668127-110736.jpg",
] as const;

export const VILLA_LOTUS_GALLERY = [
  "/images/villas/lotus/01-first.jpg",
  "/images/villas/lotus/02-img-7963.jpg",
  "/images/villas/lotus/03-img-7966.jpg",
  "/images/villas/lotus/04-img-7967.jpg",
  "/images/villas/lotus/05-img-7969.jpg",
  "/images/villas/lotus/06-img-7970.jpg",
  "/images/villas/lotus/07-img-7971.jpg",
  "/images/villas/lotus/08-img-7972.jpg",
  "/images/villas/lotus/09-img-7973.jpg",
  "/images/villas/lotus/10-img-7976.jpg",
  "/images/villas/lotus/11-img-7977.jpg",
  "/images/villas/lotus/12-img-7978.jpg",
  "/images/villas/lotus/13-img-7979.jpg",
  "/images/villas/lotus/14-img-7982.jpg",
  "/images/villas/lotus/15-img-7983.jpg",
  "/images/villas/lotus/16-last.jpg",
] as const;

export const VILLA_MONSTERA_GALLERY = [
  "/images/villas/monstera/01-first.jpg",
  "/images/villas/monstera/02-img-7936.jpg",
  "/images/villas/monstera/03-img-7938.jpg",
  "/images/villas/monstera/04-img-7941.jpg",
  "/images/villas/monstera/05-img-7944.jpg",
  "/images/villas/monstera/06-img-7946.jpg",
  "/images/villas/monstera/07-img-7950.jpg",
  "/images/villas/monstera/08-img-7951.jpg",
  "/images/villas/monstera/09-img-7952.jpg",
  "/images/villas/monstera/10-img-7953.jpg",
  "/images/villas/monstera/11-img-7955.jpg",
  "/images/villas/monstera/12-img-7956.jpg",
  "/images/villas/monstera/13-last.jpg",
] as const;

export const VILLA_TUNJUNG_GALLERY = [
  "/images/villas/tunjung/01-first.jpg",
  "/images/villas/tunjung/02-img-7878.jpg",
  "/images/villas/tunjung/03-img-7879.jpg",
  "/images/villas/tunjung/04-img-7884.jpg",
  "/images/villas/tunjung/05-img-7888.jpg",
  "/images/villas/tunjung/06-img-7890.jpg",
  "/images/villas/tunjung/07-img-7894.jpg",
  "/images/villas/tunjung/08-img-7895.jpg",
  "/images/villas/tunjung/09-img-7899.jpg",
  "/images/villas/tunjung/10-img-7902.jpg",
  "/images/villas/tunjung/11-img-7904.jpg",
  "/images/villas/tunjung/12-last.jpg",
] as const;

